### ISSUE TITLE
Parsing duration is giving the value multiplied by 10

### ISSUE THREAD

**Issue by sayeedhussain** [rickb777/date#10]
https://github.com/rickb777/date/blob/c7dda9224f958b55c21026035f688df537b10b2d/period/parse.go#L220

HI @rickb777. When I try to parse ISO8601 durations ex: PT1S, I am getting the seconds value as 10 instead of 1 due to that line of code.

**Comment by rickb777** [comment]
I've tried to reproduce an error but I would need to know more about the problem you're seeing.

Line 220 is correct as it stands. The internal stored value is fixed-point ten times bigger than the number it represents, e.g. `10` in the seconds field represents `PT1.0S`.

BTW I experimented with changing this to 100 times bigger fixed point, but without achieving a useful benefit.

**Comment by rickb777** [comment]
Closed after no further action.

**Comment by dozer111** [comment]
for those who use debug and doesent understand what is going on)

```go
ttl := period.NewYMD(1, 0, 0)
```

is one year

When I use the debugger I see 

![img](https://github.com/user-attachments/assets/b4031632-3c48-49d1-89bc-7b7e2ea0c794)


but, try to 

```go
ttl.Year()
```

and you'll see correct expected value

**Comment by rickb777** [comment]
Yes this is how Period v1 works - it uses fixed point arithmetic to give one decimal place of precision. This is now obsolete.

The current version uses seven decimal numbers to give practically unlimited precision in all seven fields in a Period. Please see https://github.com/rickb777/period and please use https://github.com/rickb777/date/v2 instead of v1.
