### ISSUE TITLE
Between function fails if one argument is time.Now

### ISSUE THREAD

**Issue by Woody1193** [rickb777/date#18]
I tried getting a period between two dates, one of which is the current time.

```
year := 2021
month := 3

now := time.Now()
p := period.Between(time.Date(int(year), time.Month(month), 1, 0, 0, 0, 0, now.Location()), now)
```

However, this panics with the statement:
Periods must have homogeneous signs; got P0Y0M0W190DT19H3M44S

For reference, this was generated at 2021-09-07 19:07:43.2612391 +0900 JST m=+0.109965201 but this was not the only time which generated this panic. What exactly does it mean for a period to not have a homogeneous sign and how can I fix this?

**Comment by shogg** [comment]
This is not caused by `time.Now`.
`period.Between` is totally broken if the period is longer than 3276 days. It's also untested, `TestBetween` has no case where one component (year, month, day) is greater than the other.

**Comment by rickb777** [comment]
I have not been able to reproduce this issue. The daysDiff function works (only) because it is called with ordered arguments, i.e. t2 is after t1. The fixed-point 16 bit arithmetic is a core part of the design.

**Comment by shogg** [comment]
https://github.com/rickb777/date/blob/ff580cf3bbf4fdf761569a31cd129f50ab602cf3/period/period.go#L145
Here you use `daysDiff` in `period.Between`. `Between` calls `period.New`. `New` checks that all numbers are postive or negative or it panics otherwise (that's so wrong).
The main point is, `daysDiff` returns something like this: `2023/10/1`-`2023/09/21`=`0/1/-20`. Not all numbers are positive or negative.
Please correct me.
