### ISSUE TITLE
Wrong months calculation 

### ISSUE THREAD

**Issue by mmeloni** [rickb777/date#3]
Hi all,
in github.com/rickb777/date@v1.12.0
I have:
```
p, err := period.Parse("P12M")
if err != nil{
	return nil, err
}
m1 := p.TotalMonthsApprox() //12 OK
m2 := p.Months()// 0 KO
```
From doc  months() should returns the whole number of months in the period. I get 0

**Comment by rickb777** [comment]
Hi,

Sorry I didn't answer this earlier. The behaviour is as expected, although the documentation will need to be improved to explain why.

The reason is that `period.Parse("P12M")` is normalised, so it's the same as `period.Parse("P1Y")`. In this case, the number of months is 0 and the number of years is 1.

A similar thing happens, for example, with `period.Parse("PT60M")` and `period.Parse("PT1H")` - in this case the number of minutes is 0 and hours is 1. Likewise for seconds and minutes.

Just for clarification, weeks are handled slightly differently, being synthetic (there is no weeks field, only days).

**Comment by rickb777** [comment]
I have improved the documentation in v1.12.2; please feel free to create issues for any shortcomings, or anything else for that matter.
